FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    python3-dev \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.backend.txt .
RUN pip install --upgrade pip setuptools wheel
RUN pip install -r requirements.backend.txt

COPY . .

ENV PORT=8008
ENV PYTHONPATH=/app

EXPOSE 8008

CMD gunicorn -w 1 -k uvicorn.workers.UvicornWorker src.app.backend:app --bind 0.0.0.0:$PORT