FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    python3-dev \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --upgrade pip setuptools wheel
RUN pip install -r requirements.txt

COPY . .

ENV BACKEND_URL=http://backend:8008
ENV PYTHONPATH=/app

EXPOSE 8501

CMD streamlit run src/app/frontend.py --server.address=0.0.0.0 --server.port=8501